// <auto-generated />
using FM.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FM.Data.Migrations
{
    [DbContext(typeof(FootballManagerDbContext))]
    [Migration("20250309173706_ExtendedAthleteSeeder")]
    partial class ExtendedAthleteSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FM.Data.Entities.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FirstName = "Cristiano",
                            LastName = "Ronaldo",
                            Nationality = "Portugal",
                            Position = 7
                        },
                        new
                        {
                            Id = -2,
                            FirstName = "Erling",
                            LastName = "Haaland",
                            Nationality = "Norway",
                            Position = 7
                        },
                        new
                        {
                            Id = -3,
                            FirstName = "Kylian",
                            LastName = "Mbappe",
                            Nationality = "France",
                            Position = 7
                        },
                        new
                        {
                            Id = -4,
                            FirstName = "Vinicius",
                            LastName = "Junior",
                            Nationality = "Brazil",
                            Position = 8
                        },
                        new
                        {
                            Id = -5,
                            FirstName = "Luis",
                            LastName = "Diaz",
                            Nationality = "Columbia",
                            Position = 8
                        },
                        new
                        {
                            Id = -6,
                            FirstName = "Khvicha",
                            LastName = "Kvaratskhelia",
                            Nationality = "Brazil",
                            Position = 8
                        },
                        new
                        {
                            Id = -7,
                            FirstName = "Lamine",
                            LastName = "Yamal",
                            Nationality = "Spain",
                            Position = 9
                        },
                        new
                        {
                            Id = -8,
                            FirstName = "Bukayo",
                            LastName = "Saka",
                            Nationality = "England",
                            Position = 9
                        },
                        new
                        {
                            Id = -9,
                            FirstName = "Phil",
                            LastName = "Foden",
                            Nationality = "England",
                            Position = 9
                        },
                        new
                        {
                            Id = -10,
                            FirstName = "Jude",
                            LastName = "Bellingham",
                            Nationality = "England",
                            Position = 5
                        },
                        new
                        {
                            Id = -11,
                            FirstName = "Florian",
                            LastName = "Wirtz",
                            Nationality = "Germany",
                            Position = 5
                        },
                        new
                        {
                            Id = -12,
                            FirstName = "Jamal",
                            LastName = "Musiala",
                            Nationality = "Germany",
                            Position = 5
                        },
                        new
                        {
                            Id = -13,
                            FirstName = "Cole",
                            LastName = "Palmer",
                            Nationality = "England",
                            Position = 5
                        },
                        new
                        {
                            Id = -14,
                            FirstName = "Federico",
                            LastName = "Valverde",
                            Nationality = "Uruguay",
                            Position = 4
                        },
                        new
                        {
                            Id = -15,
                            FirstName = "Declan",
                            LastName = "Rice",
                            Nationality = "England",
                            Position = 4
                        },
                        new
                        {
                            Id = -16,
                            FirstName = "Eduardo",
                            LastName = "Camavinga",
                            Nationality = "France",
                            Position = 4
                        },
                        new
                        {
                            Id = -17,
                            FirstName = "Alexis",
                            LastName = "Mac Allister",
                            Nationality = "Argentina",
                            Position = 4
                        },
                        new
                        {
                            Id = -18,
                            FirstName = "Nicolo",
                            LastName = "Barella",
                            Nationality = "Italy",
                            Position = 4
                        },
                        new
                        {
                            Id = -19,
                            FirstName = "Enzo",
                            LastName = "Fernandez",
                            Nationality = "Argentina",
                            Position = 4
                        },
                        new
                        {
                            Id = -20,
                            FirstName = "Dominik",
                            LastName = "Szoboszlai",
                            Nationality = "Hungary",
                            Position = 4
                        },
                        new
                        {
                            Id = -21,
                            FirstName = "Moises",
                            LastName = "Caicedo",
                            Nationality = "Ecuador",
                            Position = 6
                        },
                        new
                        {
                            Id = -22,
                            FirstName = "Bruno",
                            LastName = "Guimaraes",
                            Nationality = "Brazil",
                            Position = 6
                        },
                        new
                        {
                            Id = -23,
                            FirstName = "Aurélien",
                            LastName = "Tchouaméni",
                            Nationality = "France",
                            Position = 6
                        },
                        new
                        {
                            Id = -24,
                            FirstName = "Joao",
                            LastName = "Neves",
                            Nationality = "Portugal",
                            Position = 6
                        },
                        new
                        {
                            Id = -25,
                            FirstName = "Martin",
                            LastName = "Zubimendi",
                            Nationality = "Spain",
                            Position = 6
                        },
                        new
                        {
                            Id = -26,
                            FirstName = "William",
                            LastName = "Saliba",
                            Nationality = "France",
                            Position = 3
                        },
                        new
                        {
                            Id = -27,
                            FirstName = "Josko",
                            LastName = "Gvardiol",
                            Nationality = "Croatia",
                            Position = 2
                        },
                        new
                        {
                            Id = -28,
                            FirstName = "Gabriel",
                            LastName = "Magalhaes",
                            Nationality = "Brazil",
                            Position = 3
                        },
                        new
                        {
                            Id = -29,
                            FirstName = "Alessandro",
                            LastName = "Bastoni",
                            Nationality = "Italy",
                            Position = 3
                        },
                        new
                        {
                            Id = -30,
                            FirstName = "Trent",
                            LastName = "Alexander-Arnold",
                            Nationality = "England",
                            Position = 1
                        },
                        new
                        {
                            Id = -31,
                            FirstName = "Ruben",
                            LastName = "Dias",
                            Nationality = "Portugal",
                            Position = 3
                        },
                        new
                        {
                            Id = -32,
                            FirstName = "Pau",
                            LastName = "Cubarsi",
                            Nationality = "Spain",
                            Position = 3
                        },
                        new
                        {
                            Id = -33,
                            FirstName = "Cristian",
                            LastName = "Romero",
                            Nationality = "Argentina",
                            Position = 3
                        },
                        new
                        {
                            Id = -34,
                            FirstName = "Jules",
                            LastName = "Kounde",
                            Nationality = "France",
                            Position = 1
                        },
                        new
                        {
                            Id = -35,
                            FirstName = "Achraf",
                            LastName = "Hakimi",
                            Nationality = "Morroco",
                            Position = 1
                        },
                        new
                        {
                            Id = -36,
                            FirstName = "Federico",
                            LastName = "Dimarco",
                            Nationality = "Italy",
                            Position = 2
                        },
                        new
                        {
                            Id = -37,
                            FirstName = "Nunu",
                            LastName = "Mendes",
                            Nationality = "Portugal",
                            Position = 2
                        },
                        new
                        {
                            Id = -38,
                            FirstName = "Alejandro",
                            LastName = "Balde",
                            Nationality = "Spain",
                            Position = 2
                        },
                        new
                        {
                            Id = -39,
                            FirstName = "Giorgi",
                            LastName = "Mamardashvilli",
                            Nationality = "Georgia",
                            Position = 0
                        },
                        new
                        {
                            Id = -40,
                            FirstName = "Diogo",
                            LastName = "Costa",
                            Nationality = "Portugal",
                            Position = 0
                        },
                        new
                        {
                            Id = -41,
                            FirstName = "David",
                            LastName = "Raya",
                            Nationality = "Spain",
                            Position = 0
                        },
                        new
                        {
                            Id = -42,
                            FirstName = "Gregor",
                            LastName = "Kobel",
                            Nationality = "Switzerland",
                            Position = 0
                        },
                        new
                        {
                            Id = -43,
                            FirstName = "Gianluigi",
                            LastName = "Donnarumma",
                            Nationality = "Italy",
                            Position = 0
                        },
                        new
                        {
                            Id = -44,
                            FirstName = "Guglielmo",
                            LastName = "Vicario",
                            Nationality = "Italy",
                            Position = 0
                        },
                        new
                        {
                            Id = -45,
                            FirstName = "Andre",
                            LastName = "Onana",
                            Nationality = "Cameroon",
                            Position = 0
                        },
                        new
                        {
                            Id = -46,
                            FirstName = "Mike",
                            LastName = "Maignan",
                            Nationality = "France",
                            Position = 0
                        },
                        new
                        {
                            Id = -47,
                            FirstName = "Lucas",
                            LastName = "Chevalier",
                            Nationality = "France",
                            Position = 0
                        },
                        new
                        {
                            Id = -48,
                            FirstName = "Unai",
                            LastName = "Simon",
                            Nationality = "Spain",
                            Position = 0
                        },
                        new
                        {
                            Id = -49,
                            FirstName = "Anatoliy",
                            LastName = "Trubin",
                            Nationality = "Ukraine",
                            Position = 0
                        });
                });

            modelBuilder.Entity("FM.Data.Entities.AthleteTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("TeamId");

                    b.ToTable("AthleteTeam");
                });

            modelBuilder.Entity("FM.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FM.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FM.Data.Entities.AthleteTeam", b =>
                {
                    b.HasOne("FM.Data.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FM.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FM.Data.Entities.Team", b =>
                {
                    b.HasOne("FM.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
